// this file is autogenerated by generate.js - https://github.com/menduz/zig-steamworks
#import "steam_api.h"
#import "steam_gameserver.h"

extern "C" void* CustomSteamClientGetter() { return SteamClient(); }